steps:
- name: "gcr.io/kaniko-project/executor:latest"
  args: ["--destination=gcr.io/mlops-insights-data-sweden/prediction-container:latest",
         "--cache=false",
         "--cache-ttl=99h"]
  env: ["AIP_STORAGE_URI=gs://mlops-insights-data-swedenmovielens/artifacts",
        "PROJECT_ID=mlops-insights-data-sweden",
        "LOGGER_PUBSUB_TOPIC=logger-pubsub-topic"]
options:
  machineType: "E2_HIGHCPU_8"
